Repository UBC-MDS/DSCI524_Text_Analyzer_19, pull requests merged in 2025-01, with the labels that each got.

#28 Add codes in the extract-keywords function
  src/textanalyzer/extract_keywords.py
  tests/test_extract_keywords.py
Labels: documentation, enhancement

#27 Topic modeling function script + tests + dependency update
  README.md
  poetry.lock
  pyproject.toml
  src/textanalyzer/extract_keywords.py
  src/textanalyzer/topic_modeling.py
  tests/test_topic_modeling.py
Labels: documentation, enhancement

#40 Topic modeling example + ci fixes
  README.md
  docs/topic_modeling.ipynb
  src/textanalyzer/topic_modeling.py
  tests/test_topic_modeling.py
Labels: bug, documentation, enhancement

#63 Cdfix + address feedbacks
  README.md
  docs/example.ipynb
  pyproject.toml
  src/messageanalyzer/detect_language_patterns.py
  src/messageanalyzer/extract_keywords.py
  src/messageanalyzer/sentiment_analysis.py
  src/messageanalyzer/topic_modeling.py
Labels: bug, documentation, enhancement, help wanted
